"""Generate `docs/api.md`, the endpoint reference, from the app's own OpenAPI schema.

The routes, their query parameters and their request/response models are read off the FastAPI
app, so the reference cannot list an endpoint that does not exist or miss one that does. A test
compares the committed file against a fresh render; after changing a route, regenerate it with:

    uv run python -m scripts.api_doc
"""

from pathlib import Path
from typing import Any

BACKEND_DIR = Path(__file__).resolve().parent.parent
OUTPUT = BACKEND_DIR.parent / "docs" / "api.md"

_PREFIX = "/api/v1"
_METHOD_ORDER = ("get", "post", "patch", "put", "delete")

_HEADER = f"""\
# API reference

<!-- Generated by `backend/scripts/api_doc.py` from the FastAPI OpenAPI schema.
     Do not edit by hand: run `uv run python -m scripts.api_doc` from `backend/`. -->

> [!NOTE]
> Generated from the running app's OpenAPI schema, so it always matches the routes.
> With the sidecar running, the interactive docs are at `http://127.0.0.1:8765/docs`.

Every path is under `{_PREFIX}`, takes a bearer token (except `register`, `login` and `health`),
and only ever sees the caller's rows. Errors use the envelope `{{error: {{code, message,
details?}}}}`. Model names refer to the Pydantic schemas in `backend/app/features/*/schemas.py`.
"""


def render(spec: dict[str, Any]) -> str:
    """Render an OpenAPI ``spec`` as the Markdown document, one table per tag."""
    by_tag: dict[str, list[str]] = {}
    for path, operations in spec["paths"].items():
        for method in _METHOD_ORDER:
            operation = operations.get(method)
            if operation is None:
                continue
            tag = (operation.get("tags") or ["other"])[0]
            by_tag.setdefault(tag, []).append(_row(path, method, operation))

    lines = [_HEADER]
    for tag, rows in by_tag.items():
        lines.extend(
            [
                f"## {tag}",
                "",
                "| Method | Path | Query | Body | Response |",
                "|--------|------|-------|------|----------|",
                *rows,
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def _row(path: str, method: str, operation: dict[str, Any]) -> str:
    query = [p["name"] for p in operation.get("parameters", []) if p["in"] == "query"]
    cells = [
        f"`{method.upper()}`",
        f"`{path.removeprefix(_PREFIX)}`",
        ", ".join(f"`{name}`" for name in query),
        _body(operation),
        _response(operation),
    ]
    return "| " + " | ".join(cells) + " |"


def _body(operation: dict[str, Any]) -> str:
    content = operation.get("requestBody", {}).get("content", {})
    if "multipart/form-data" in content:
        return "multipart"
    if "application/json" in content:
        return _schema_name(content["application/json"]["schema"])
    return ""


def _response(operation: dict[str, Any]) -> str:
    """The success status and its model, e.g. ``201 AccountRead``."""
    for status, response in operation["responses"].items():
        if not status.startswith("2"):
            continue
        content = response.get("content", {})
        schema = content.get("application/json", {}).get("schema")
        if schema is None or schema == {}:
            return status
        return f"{status} {_schema_name(schema)}"
    return ""


def _schema_name(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return f"`{schema['$ref'].rsplit('/', 1)[-1]}`"
    if schema.get("type") == "array":
        return f"[{_schema_name(schema.get('items', {}))}]"
    return f"`{schema.get('type', 'object')}`"


def main() -> None:
    from app.main import create_app

    OUTPUT.write_text(render(create_app().openapi()), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(BACKEND_DIR.parent)}")


if __name__ == "__main__":
    main()
