"""Generate `docs/database.md`, the schema reference, from a freshly migrated database.

The document is reflected from what Alembic actually builds, not hand-written and not read off
the ORM models, so it cannot describe a column the migrations never created. A test compares the
committed file against a fresh render; after changing a migration, regenerate it with:

    uv run python -m scripts.schema_doc
"""

import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

from sqlalchemy import Engine, create_engine, inspect

BACKEND_DIR = Path(__file__).resolve().parent.parent
OUTPUT = BACKEND_DIR.parent / "docs" / "database.md"

#: Alembic's own bookkeeping, not part of the application schema.
_IGNORED_TABLES = {"alembic_version"}

#: Reflected SQLite type → the coarse name the diagram prints. Lengths and precision are
#: implementation detail; what an agent needs is "integer", never "is this a float".
_TYPE_NAMES = {
    "VARCHAR": "text",
    "TEXT": "text",
    "INTEGER": "int",
    "BIGINTEGER": "int",
    "BOOLEAN": "bool",
    "DATE": "date",
    "DATETIME": "datetime",
    "FLOAT": "real",
    "REAL": "real",
    "NUMERIC": "numeric",
    "JSON": "json",
}

_HEADER = """\
# Database schema

<!-- Generated by `backend/scripts/schema_doc.py` from a freshly migrated database.
     Do not edit by hand: run `uv run python -m scripts.schema_doc` from `backend/`. -->

> [!NOTE]
> Generated from the Alembic migrations at head, so it always matches the real schema. The
> conventions and the reasoning behind each table live in [`PROJECT.md`](../PROJECT.md) §4.

Conventions visible below: primary keys are UUID strings, money columns end in `_minor`
(signed integer minor units), rates end in `_bps` (integer basis points), and timestamps are
UTC.
"""


def render(engine: Engine) -> str:
    """Render the schema reachable through ``engine`` as the Markdown document."""
    inspector = inspect(engine)
    tables = sorted(set(inspector.get_table_names()) - _IGNORED_TABLES)
    reflected = {name: _reflect(inspector, name) for name in tables}

    lines = [_HEADER, "## Entity-relationship diagram", "", "```mermaid", "erDiagram"]
    for name in tables:
        lines.extend(_entity(name, reflected[name]))
    for name in tables:
        lines.extend(_relationships(name, reflected[name]))
    lines.extend(["```", "", "## Constraints", ""])
    for name in tables:
        lines.extend(_constraints(name, reflected[name]))
    return "\n".join(lines).rstrip() + "\n"


def _reflect(inspector: Any, table: str) -> dict[str, Any]:
    """Everything the document prints about one table."""
    return {
        "columns": inspector.get_columns(table),
        "pk": set(inspector.get_pk_constraint(table)["constrained_columns"]),
        "fks": inspector.get_foreign_keys(table),
        "uniques": inspector.get_unique_constraints(table),
        "indexes": inspector.get_indexes(table),
        "checks": inspector.get_check_constraints(table),
    }


def _single_column_uniques(info: dict[str, Any]) -> set[str]:
    """Columns unique on their own, whether by constraint or by unique index."""
    groups = [u["column_names"] for u in info["uniques"]]
    groups += [i["column_names"] for i in info["indexes"] if i["unique"]]
    return {cols[0] for cols in groups if len(cols) == 1}


def _entity(name: str, info: dict[str, Any]) -> list[str]:
    fk_columns = {col for fk in info["fks"] for col in fk["constrained_columns"]}
    uniques = _single_column_uniques(info)
    lines = [f"    {name} {{"]
    for column in info["columns"]:
        col = column["name"]
        keys = [
            key
            for key, present in (
                ("PK", col in info["pk"]),
                ("FK", col in fk_columns),
                ("UK", col in uniques),
            )
            if present
        ]
        line = f"        {_type_name(column['type'])} {col}"
        if keys:
            line += " " + ", ".join(keys)
        if column["nullable"] and col not in info["pk"]:
            line += ' "nullable"'
        lines.append(line)
    lines.append("    }")
    return lines


def _relationships(name: str, info: dict[str, Any]) -> list[str]:
    """One line per foreign key, drawn from the referenced table to this one."""
    nullable = {column["name"] for column in info["columns"] if column["nullable"]}
    uniques = _single_column_uniques(info)
    lines = []
    for fk in sorted(info["fks"], key=lambda fk: fk["constrained_columns"]):
        cols = fk["constrained_columns"]
        parent = "|o" if any(col in nullable for col in cols) else "||"
        child = "o|" if len(cols) == 1 and cols[0] in uniques else "o{"
        lines.append(f'    {fk["referred_table"]} {parent}--{child} {name} : "{", ".join(cols)}"')
    return lines


def _constraints(name: str, info: dict[str, Any]) -> list[str]:
    """The rules the diagram cannot show: composite uniques, checks, and FK delete actions."""
    items = []
    for unique in info["uniques"]:
        if len(unique["column_names"]) > 1:
            items.append(f"unique `({', '.join(unique['column_names'])})`")
    for index in info["indexes"]:
        if index["unique"] and len(index["column_names"]) > 1:
            items.append(f"unique `({', '.join(index['column_names'])})`")
    for check in sorted(info["checks"], key=lambda check: check["sqltext"]):
        items.append(f"check `{' '.join(check['sqltext'].split())}`")
    for fk in info["fks"]:
        ondelete = (fk.get("options") or {}).get("ondelete")
        if ondelete:
            cols = ", ".join(fk["constrained_columns"])
            items.append(f"`{cols}` → `{fk['referred_table']}` on delete {ondelete.lower()}")
    if not items:
        return []
    return [f"### `{name}`", "", *(f"- {item}" for item in items), ""]


def _type_name(sql_type: Any) -> str:
    raw = type(sql_type).__name__.upper()
    return _TYPE_NAMES.get(raw, raw.lower())


def _migrated_engine(db_path: Path) -> Engine:
    """Bring an empty SQLite file to head with the Alembic CLI and return an engine on it."""
    env = {**os.environ, "FINSTRIDE_DB_PATH": str(db_path)}
    subprocess.run(
        [sys.executable, "-m", "alembic", "upgrade", "head"],
        cwd=BACKEND_DIR,
        env=env,
        check=True,
        capture_output=True,
    )
    return create_engine(f"sqlite:///{db_path}")


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        engine = _migrated_engine(Path(tmp) / "schema.db")
        try:
            document = render(engine)
        finally:
            engine.dispose()
    OUTPUT.write_text(document, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(BACKEND_DIR.parent)}")


if __name__ == "__main__":
    main()
